### ISSUE TITLE
Feature Request: Prediction Success Rate / Money Gained

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#9]
Implementing a way to see prediction success rate and money earned/lost since program start.

WIP

**Comment by xxxFRIARxxx** [comment]
https://github.com/xxxFRIARxxx/SaltyBot/blob/c75fa615511167b6cbb55c393502adcbce595c30/SaltyDatabase.py#L65-L69

Just so you don't double your work:  The code above already shows you your prediction success rate (since the DB was created).  Did you plan on making something that showed you the success rate for the last X matches, or maybe for the current session?

**Comment by zappybiby** [comment]
Ok that is good to know! I think I can create a way to track progress using that entry in the database then. My plan is to eventually find a way to graph/visualize how the program's success rate has changed over time, especially if we are considering implementing machine learning in the future. I'm also looking into a way to show how much the program has earned/lost in the current session.

**Comment by xxxFRIARxxx** [comment]
Sorry, but I've beaten you to the punch.  👊 

Implemented the previous_bet_amount() this morning, and just updated!

Let me know if you'd like any other features.
